on:
  schedule:
    - cron: '00 14 * * *'
      # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

name: WLS Daily COVID Note

jobs:
  render:
    name: WLS Daily COVID Note
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - name: Set up pandoc for Rmd docs
        uses: r-lib/actions/setup-pandoc@v2
      - name: Install dependencies and packages
        run: Rscript -e 'install.packages(c("stringr","readr","dplyr","sf","leaflet","htmlwidgets","leaflet.providers","leaflet.extras"))'
      - name: Gather data and save as text file
        run: Rscript scripts/fires_scrape_build.R
      - name: Commit results
        run: |
          git add -A
          git commit -m 'New fires data. Maps updated!' || echo "No changes"
          git push origin || echo "No changes to commit"
