on:
  schedule:
    - cron: '20 18 * * *'
      # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

name: WLS Daily COVID Note

jobs:
  render:
    name: Automate COVID Note
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - name: Set up pandoc for Rmd docs
        uses: r-lib/actions/setup-pandoc@v2
      - name: Install dependencies and packages
        run: Rscript -e 'install.packages(c("readr","dplyr","lubridate"))'
      - name: Gather data and save as text file
        run: Rscript scripts/chi_covid_note.R
      - name: Commit results
        run: |
          git add -A
          git commit -m 'New COVID note saved' || echo "No changes"
          git push origin || echo "No changes to commit"
      - name: Send email with contents
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Daily WLS COVID Note
          to: john.l.kelly@disney.com,jkelly3rd@gmail.com
          from: ABC OTV Data Team #<abcotvdatateam@gmail.com>
          secure: true
          # body: Words
          # Optional HTML body read from file:
          html_body: file://note.txt
          # Optional carbon copy recipients:
          cc: john.l.kelly@abc.com
          convert_markdown: true