on:
  schedule:
    - cron: '20 18 * * *'
      # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

name: WLS Daily COVID Note

jobs:
  render:
    name: Automate COVID Note
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - name: Set up pandoc for Rmd docs
        uses: r-lib/actions/setup-pandoc@v2
      - name: Install dependencies and packages
        run: Rscript -e 'install.packages(c("readr","dplyr","lubridate"))'
      - name: Gather data and save as text file
        run: Rscript scripts/chi_covid_note.R
      - name: Commit results
        run: |
          git add -A
          git commit -m 'New COVID note saved' || echo "No changes"
          git push origin || echo "No changes to commit"
      - name: Send email with contents
uses: dawidd6/action-send-mail@v3
with:
  # Required mail server address:
  server_address: smtp.gmail.com
# Required mail server port:
server_port: 465
# Optional (recommended): mail server username:
username: ${{secrets.MAIL_USERNAME}}
# Optional (recommended) mail server password:
password: ${{secrets.MAIL_PASSWORD}}
# Required mail subject:
subject: Daily WLS COVID Note
# Required recipients' addresses:
to: john.l.kelly@disney.com,jkelly3rd@gmail.com
# Required sender full name (address can be skipped):
from: ABC OTV Data Team # <abcotvdatateam@gmail.com>
# Optional whether this connection use TLS (default is true if server_port is 465)
secure: true
# Optional plain body:
# body: Words
# Optional HTML body read from file:
html_body: file://note.txt
# Optional carbon copy recipients:
cc: john.l.kelly@abc.com
# Optional blind carbon copy recipients:
# bcc: abcxyz@gmail.com,abcxyz@gmail.com
# Optional converting Markdown to HTML (set content_type to text/html too):
convert_markdown: true